
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 56;
  public static final int READLINE = 15;
  public static final int GT = 68;
  public static final int IMPLEMENTS = 4;
  public static final int CONST = 9;
  public static final int ITOD = 25;
  public static final int NOTEQ = 65;
  public static final int ITOB = 27;
  public static final int ARITHAND = 88;
  public static final int FLOATCONST = 99;
  public static final int UNTIL = 39;
  public static final int LEFTAKULAD = 80;
  public static final int SIZEOF = 50;
  public static final int COMMA = 74;
  public static final int ARITHOR = 90;
  public static final int DIVASS = 85;
  public static final int ADDASS = 82;
  public static final int LT = 66;
  public static final int ANDAND = 70;
  public static final int CHARCONST = 100;
  public static final int OROR = 71;
  public static final int DOUBLE = 37;
  public static final int BOOLEANCONST = 95;
  public static final int PROTECTED = 29;
  public static final int NOT = 86;
  public static final int __FUNC__ = 43;
  public static final int DEC = 23;
  public static final int FLOAT = 8;
  public static final int INTCONST = 96;
  public static final int RECORD = 45;
  public static final int READINTEGER = 14;
  public static final int LOGICAND = 89;
  public static final int RIGHTBRACK = 77;
  public static final int MOD = 62;
  public static final int CLASS = 18;
  public static final int BRACKETS = 57;
  public static final int RIGHTPAREN = 79;
  public static final int __LINE__ = 41;
  public static final int LONG = 21;
  public static final int PLUS = 58;
  public static final int WHILE = 30;
  public static final int EXTENDS = 3;
  public static final int MULTASS = 84;
  public static final int ASSIGN = 63;
  public static final int INTERFACE = 19;
  public static final int CHAR = 49;
  public static final int DOUBLECONST = 97;
  public static final int SWITCH = 53;
  public static final int FOR = 5;
  public static final int EXTERN = 94;
  public static final int VOID = 16;
  public static final int DIV = 61;
  public static final int PUBLIC = 35;
  public static final int RETURN = 33;
  public static final int MULT = 60;
  public static final int ELSE = 32;
  public static final int BREAK = 34;
  public static final int GTEQ = 69;
  public static final int DOT = 75;
  public static final int INT = 36;
  public static final int NULL = 20;
  public static final int EQEQ = 64;
  public static final int SEMICOLON = 73;
  public static final int EOF = 0;
  public static final int THIS = 2;
  public static final int DEFAULT = 51;
  public static final int PRINT = 13;
  public static final int FUNCTION = 42;
  public static final int SUBASS = 83;
  public static final int INC = 22;
  public static final int REPEAT = 11;
  public static final int IMPORT = 40;
  public static final int LOGICSIGHN = 72;
  public static final int MINUS = 59;
  public static final int LONGCONST = 101;
  public static final int LTEQ = 67;
  public static final int IN = 55;
  public static final int error = 1;
  public static final int CONTINUE = 6;
  public static final int BITNEG = 87;
  public static final int IF = 31;
  public static final int ID = 17;
  public static final int LEFTBRACK = 76;
  public static final int OF = 47;
  public static final int END = 46;
  public static final int COLON = 93;
  public static final int EXTERND = 48;
  public static final int LEFTPAREN = 78;
  public static final int FOREACH = 12;
  public static final int BEGIN = 44;
  public static final int CASE = 52;
  public static final int RIGHTAKULAD = 81;
  public static final int BTOI = 26;
  public static final int NEW = 7;
  public static final int STRING = 38;
  public static final int NEWARRAY = 10;
  public static final int STRINGCONST = 98;
  public static final int DTOI = 24;
  public static final int LOGICOR = 91;
  public static final int PRIVATE = 28;
  public static final int XOR = 92;
  public static final int AUTO = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "CONTINUE",
  "NEW",
  "FLOAT",
  "CONST",
  "NEWARRAY",
  "REPEAT",
  "FOREACH",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "VOID",
  "ID",
  "CLASS",
  "INTERFACE",
  "NULL",
  "LONG",
  "INC",
  "DEC",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "PRIVATE",
  "PROTECTED",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "PUBLIC",
  "INT",
  "DOUBLE",
  "STRING",
  "UNTIL",
  "IMPORT",
  "__LINE__",
  "FUNCTION",
  "__FUNC__",
  "BEGIN",
  "RECORD",
  "END",
  "OF",
  "EXTERND",
  "CHAR",
  "SIZEOF",
  "DEFAULT",
  "CASE",
  "SWITCH",
  "AUTO",
  "IN",
  "BOOL",
  "BRACKETS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "ASSIGN",
  "EQEQ",
  "NOTEQ",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "ANDAND",
  "OROR",
  "LOGICSIGHN",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "LEFTBRACK",
  "RIGHTBRACK",
  "LEFTPAREN",
  "RIGHTPAREN",
  "LEFTAKULAD",
  "RIGHTAKULAD",
  "ADDASS",
  "SUBASS",
  "MULTASS",
  "DIVASS",
  "NOT",
  "BITNEG",
  "ARITHAND",
  "LOGICAND",
  "ARITHOR",
  "LOGICOR",
  "XOR",
  "COLON",
  "EXTERN",
  "BOOLEANCONST",
  "INTCONST",
  "DOUBLECONST",
  "STRINGCONST",
  "FLOATCONST",
  "CHARCONST",
  "LONGCONST"
  };
}

